[package]
name = "linuskat/iris-implot"
description = "Fork of Iris which adds 2 new plotting widgets"
license = "MIT"
authors = ["LinusKat"]
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.toml", "README.md", "LICENSE.txt", "default.project.json", "aftman.toml", "public"]

[dependencies]
